# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/batuh/qt_designer/combobox/combobox.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 606)
        MainWindow.setMinimumSize(QtCore.QSize(800, 606))
        MainWindow.setMaximumSize(QtCore.QSize(800, 606))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ıcon/Batuhan (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#centralwidget{\n"
                                 "\n"
                                 "border-image: url(:/newPrefix/combobox/ıcon/arkaplan.png);\n"
                                 "\n"
                                 "}\n"
                                 "")

        MainWindow.setIconSize(QtCore.QSize(70, 70))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_homepage = QtWidgets.QWidget()
        self.page_homepage.setObjectName("page_homepage")
        self.pushButton_go_mp3 = QtWidgets.QPushButton(self.page_homepage)
        self.pushButton_go_mp3.setGeometry(QtCore.QRect(240, 120, 381, 101))
        font = QtGui.QFont()
        font.setPointSize(2)
        self.pushButton_go_mp3.setFont(font)
        self.pushButton_go_mp3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_go_mp3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ıcon/istockphoto-1138411015-1024x1024.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_go_mp3.setIcon(icon1)
        self.pushButton_go_mp3.setIconSize(QtCore.QSize(150, 95))
        self.pushButton_go_mp3.setObjectName("pushButton_go_mp3")
        self.label_4 = QtWidgets.QLabel(self.page_homepage)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 711, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_go_mp4 = QtWidgets.QPushButton(self.page_homepage)
        self.pushButton_go_mp4.setGeometry(QtCore.QRect(240, 260, 381, 101))
        self.pushButton_go_mp4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_go_mp4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ıcon/istockphoto-878164738-170667a.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_go_mp4.setIcon(icon2)
        self.pushButton_go_mp4.setIconSize(QtCore.QSize(150, 95))
        self.pushButton_go_mp4.setObjectName("pushButton_go_mp4")
        self.pushButton_go_subtitle = QtWidgets.QPushButton(self.page_homepage)
        self.pushButton_go_subtitle.setGeometry(QtCore.QRect(240, 420, 381, 101))
        self.pushButton_go_subtitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_go_subtitle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ıcon/85722790-use-it-in-all-your-designs-filename-extension-icon-sub-subtitle-file-or-subchannel-data-file-in-flat.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_go_subtitle.setIcon(icon3)
        self.pushButton_go_subtitle.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_go_subtitle.setObjectName("pushButton_go_subtitle")
        self.stackedWidget.addWidget(self.page_homepage)
        self.page_mp3 = QtWidgets.QWidget()
        self.page_mp3.setObjectName("page_mp3")
        self.lineEdit_mp3 = QtWidgets.QLineEdit(self.page_mp3)
        self.lineEdit_mp3.setGeometry(QtCore.QRect(170, 240, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mp3.setFont(font)
        self.lineEdit_mp3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_mp3.setObjectName("lineEdit_mp3")
        self.label = QtWidgets.QLabel(self.page_mp3)
        self.label.setGeometry(QtCore.QRect(70, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_mp3 = QtWidgets.QPushButton(self.page_mp3)
        self.pushButton_mp3.setGeometry(QtCore.QRect(520, 330, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mp3.setFont(font)
        self.pushButton_mp3.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ıcon/istockphoto-1169623092-170667a.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mp3.setIcon(icon4)
        self.pushButton_mp3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_mp3.setObjectName("pushButton_mp3")
        self.label_3 = QtWidgets.QLabel(self.page_mp3)
        self.label_3.setGeometry(QtCore.QRect(310, 120, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_mp3_back = QtWidgets.QPushButton(self.page_mp3)
        self.pushButton_mp3_back.setGeometry(QtCore.QRect(0, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mp3_back.setFont(font)
        self.pushButton_mp3_back.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_mp3_back.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../ıcon/1834400-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mp3_back.setIcon(icon5)
        self.pushButton_mp3_back.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_mp3_back.setAutoRepeat(False)
        self.pushButton_mp3_back.setAutoExclusive(False)
        self.pushButton_mp3_back.setObjectName("pushButton_mp3_back")
        self.pushButton_browse_mp3 = QtWidgets.QPushButton(self.page_mp3)
        self.pushButton_browse_mp3.setGeometry(QtCore.QRect(690, 240, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_browse_mp3.setFont(font)
        self.pushButton_browse_mp3.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../ıcon/img_314990.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_browse_mp3.setIcon(icon6)
        self.pushButton_browse_mp3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_browse_mp3.setObjectName("pushButton_browse_mp3")
        self.stackedWidget.addWidget(self.page_mp3)
        self.page_mp4 = QtWidgets.QWidget()
        self.page_mp4.setObjectName("page_mp4")
        self.label_5 = QtWidgets.QLabel(self.page_mp4)
        self.label_5.setGeometry(QtCore.QRect(310, 130, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.page_mp4)
        self.label_2.setGeometry(QtCore.QRect(80, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_mp4 = QtWidgets.QLineEdit(self.page_mp4)
        self.lineEdit_mp4.setGeometry(QtCore.QRect(160, 250, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mp4.setFont(font)
        self.lineEdit_mp4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_mp4.setObjectName("lineEdit_mp4")
        self.pushButton_mp4 = QtWidgets.QPushButton(self.page_mp4)
        self.pushButton_mp4.setGeometry(QtCore.QRect(510, 350, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mp4.setFont(font)
        self.pushButton_mp4.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_mp4.setIcon(icon4)
        self.pushButton_mp4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_mp4.setObjectName("pushButton_mp4")
        self.pushButton_mp4_back = QtWidgets.QPushButton(self.page_mp4)
        self.pushButton_mp4_back.setGeometry(QtCore.QRect(0, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mp4_back.setFont(font)
        self.pushButton_mp4_back.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_mp4_back.setText("")
        self.pushButton_mp4_back.setIcon(icon5)
        self.pushButton_mp4_back.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_mp4_back.setAutoRepeat(False)
        self.pushButton_mp4_back.setAutoExclusive(False)
        self.pushButton_mp4_back.setObjectName("pushButton_mp4_back")
        self.pushButton_browse_mp4 = QtWidgets.QPushButton(self.page_mp4)
        self.pushButton_browse_mp4.setGeometry(QtCore.QRect(680, 250, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_browse_mp4.setFont(font)
        self.pushButton_browse_mp4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_browse_mp4.setIcon(icon6)
        self.pushButton_browse_mp4.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_browse_mp4.setObjectName("pushButton_browse_mp4")
        self.stackedWidget.addWidget(self.page_mp4)
        self.page_subtitle = QtWidgets.QWidget()
        self.page_subtitle.setObjectName("page_subtitle")
        self.label_11 = QtWidgets.QLabel(self.page_subtitle)
        self.label_11.setGeometry(QtCore.QRect(290, 140, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_subtitle_back = QtWidgets.QPushButton(self.page_subtitle)
        self.pushButton_subtitle_back.setGeometry(QtCore.QRect(0, 0, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_subtitle_back.setFont(font)
        self.pushButton_subtitle_back.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_subtitle_back.setText("")
        self.pushButton_subtitle_back.setIcon(icon5)
        self.pushButton_subtitle_back.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_subtitle_back.setAutoRepeat(False)
        self.pushButton_subtitle_back.setAutoExclusive(False)
        self.pushButton_subtitle_back.setObjectName("pushButton_subtitle_back")
        self.lineEdit_subtitle = QtWidgets.QLineEdit(self.page_subtitle)
        self.lineEdit_subtitle.setGeometry(QtCore.QRect(160, 240, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subtitle.setFont(font)
        self.lineEdit_subtitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_subtitle.setObjectName("lineEdit_subtitle")
        self.label_12 = QtWidgets.QLabel(self.page_subtitle)
        self.label_12.setGeometry(QtCore.QRect(70, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_browse_subtitle = QtWidgets.QPushButton(self.page_subtitle)
        self.pushButton_browse_subtitle.setGeometry(QtCore.QRect(690, 240, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_browse_subtitle.setFont(font)
        self.pushButton_browse_subtitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_browse_subtitle.setIcon(icon6)
        self.pushButton_browse_subtitle.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_browse_subtitle.setObjectName("pushButton_browse_subtitle")
        self.pushButton_subtitle = QtWidgets.QPushButton(self.page_subtitle)
        self.pushButton_subtitle.setGeometry(QtCore.QRect(510, 330, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_subtitle.setFont(font)
        self.pushButton_subtitle.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_subtitle.setIcon(icon4)
        self.pushButton_subtitle.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_subtitle.setObjectName("pushButton_subtitle")
        self.stackedWidget.addWidget(self.page_subtitle)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../ıcon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setObjectName("actionHelp")
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "MP3 , MP4 OR SUBTITLE PLEASE CHOOSE"))
        self.label.setText(_translate("MainWindow", "URL :"))
        self.pushButton_mp3.setText(_translate("MainWindow", "Convert"))
        self.label_3.setText(_translate("MainWindow", "MP3 CONVERTER"))
        self.pushButton_browse_mp3.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "MP4 CONVERTER"))
        self.label_2.setText(_translate("MainWindow", "URL :"))
        self.pushButton_mp4.setText(_translate("MainWindow", "Convert"))
        self.pushButton_browse_mp4.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "SUBTITLE CONVERTER"))
        self.label_12.setText(_translate("MainWindow", "URL :"))
        self.pushButton_browse_subtitle.setText(_translate("MainWindow", "Browse"))
        self.pushButton_subtitle.setText(_translate("MainWindow", "Convert"))
        self.menuHelp.setTitle(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))

import icons_rc
